openapi: 3.0.0
info:
  title: IRS Domain Data - Authorized Attributes
  description: Endpoints for New BTA Authorization 
  version: '0.01'
paths:
  /authorized-attributes:
    get:
      summary: Retrieve the list of attributes for a role
      parameters:
        - name: role
          in: header
          description: The user's role
          required: true
          schema:
            $ref: '#/components/schemas/BusinessAccountRoleName'
        - name: applicationID
          in: header
          description: The calling application
          required: false
          schema:
            $ref: '#/components/schemas/ApplicationID'

      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/AuthorizationAttributesObject'
                      
      tags:
        - Role Attributes

    post: 
      summary: Add a new set of rules for a role
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthorizationAttributesObject'
      responses:
        '201':
          description: Creation successful
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/AuthorizationAttributesObject'

      tags:
        - Role Attributes
    
    put:
      summary: Set the list of attributes for a role
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthorizationAttributesObject'
      responses:
        '201':
          description: Update successful, returns updated role attributes
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/AuthorizationAttributesObject"
      tags:
        - Role Attributes
  
    delete:
      summary: Remove attributes for a role
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthorizationAttributesObject'
      responses:
        '200':
          description: Delete successful
  
      tags:
        - Role Attributes

  /business-user-attributes:
    get:
      summary: Retrieve the list of attributes for the user
      parameters:
        - name: userTIN
          in: header
          description: The user's TIN
          required: true
          schema: 
            $ref: '#/components/schemas/TaxpayerIdentificationNumber'
        - name: businessEIN
          in: header
          description: The business EIN that the user is logged in for
          required: true
          schema:
            $ref: '#/components/schemas/EmployerIdentificationNumber'
      responses:
        '200':
          description: User attributes successfully retrieved
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/UserAttributesObject"
      tags:
        - User Attributes
    
    post:
      summary: Create attributes for a user
      requestBody:
        required: true 
        content:
          application/json: 
            schema:
              $ref: '#/components/schemas/UserAttributesObject'
      responses:
        '201': 
          description: Role updated, returns the updated attributes for the user
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/UserAttributesObject'
      tags:
        - User Attributes
    put:
      summary: Set the attributes for a user
      requestBody:
        required: true 
        content:
          application/json: 
            schema:
              $ref: '#/components/schemas/UserAttributesObject'
      responses:
        '201': 
          description: Attributes saved, returns the attributes for the user
          content:
            application/json: 
              schema:
                $ref: '#/components/schemas/UserAttributesObject'
      tags:
        - User Attributes
    delete:
      summary: Delete attributes for user
      requestBody:
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/UserAttributesObject'
      responses:
        '200':
          description: User attribute object deleted
      tags:
        - User Attributes
            
components:
  schemas:
    BusinessAccountRoleName:
      type: string
      description: The role a user plays in association with an organization
      enum:
        - 'Designated Officer'
        - 'Designated Employee'
        - 'Sole Proprietor'
        - 'Partner'
        - 'Shareholder'

    EmployerIdentificationNumber:
      type: string
      pattern: ^[0-9]{9}$
      example: '123456789'
    
    TaxpayerIdentificationNumber:
      type: string
      pattern: ^[0-9]{9}$
      example: '123456789'
    
    ApplicationID:
      type: string 
      description: The application that is calling the service
      enum:
        - 'Business Tax Account'
        - 'Clean Energy'
        - 'Tax Pro'
    
    AuthorizationAttributesObject:
      type: object
      required:
        - role
        - attributes
      properties:
        role: 
          $ref: '#/components/schemas/BusinessAccountRoleName'
        applicationID:
          $ref: '#/components/schemas/ApplicationID'
        attributes: 
          type: array
          items:
            $ref: '#/components/schemas/AuthorizationAttribute'
          example: [txp.bta.api.accountBalance, txp.bta.api.BTCR, txp.bta.api.getTranscript]
    
    UserAttributesObject:
      type: object
      properties:
        userTIN: 
          $ref: "#/components/schemas/TaxpayerIdentificationNumber"
        businessEIN:
          $ref: '#/components/schemas/EmployerIdentificationNumber'
        userAttributes: 
          type: array
          items:
            type: string
      
      
    
    AuthorizationAttribute:
      type: string
      description: An attribute representing a BTA resource a user may view/access
      enum:
        - txp.bta.ui.accountHome
        - txp.bta.ui.accountHome.accountStatus
        - txp.bta.ui.accountHome.records
        - txp.bta.ui.accountHome.payments
        - txp.bta.ui.accountHome.accountAccess
        - txp.bta.ui.accountHome.businessInformation
        - txp.bta.ui.accountBalance
        - txp.bta.ui.payments
        - txp.bta.ui.payments.makeAPayment
        - txp.bta.ui.payments.paymentActivity
        - txp.bta.ui.taxRecords
        - txp.bta.ui.taxRecords.taxTranscripts
        - txp.bta.ui.taxRecords.TCAU
        - txp.bta.ui.taxRecords.BTCR
        - txp.bta.ui.noticesAndLetters
        - txp.bta.ui.authorizations
        - txp.bta.ui.cleanEnergy
        - txp.bta.ui.businessProfile
        - txp.bta.ui.businessProfile.businessInformation
        - txp.bta.ui.businessProfile.businessInformation.businessDetails
        - txp.bta.ui.businessProfile.businessInformation.address
        - txp.bta.ui.businessProfile.businessInformation.emailAndPassword
        - txp.bta.ui.businessProfile.manageBusinessUsers
        - txp.bta.ui.businessProfile.wallet
        - txp.bta.api.accountSummary
        - txp.bta.api.accountBalance
        - txp.bta.api.getListOfTranscripts 
        - txp.bta.api.getTranscript
        - txp.bta.api.BTCR
        - txp.bta.api.TCAU
        - txp.bta.api.organization
        - txp.bta.api.createBusinessAccountRole
        - txp.bta.api.updateBusinessAccountRole
        - txp.bta.api.removeBusinessAccountRole
        - txp.bta.api.getNotice
        - txp.bta.api.getListOfNotices
        - txp.bta.api.getPayableBalancesDue
        - txp.bta.api.makePayment
        - txp.bta.api.cancelPayment
        - txp.bta.api.paymentActivity
        - txp.bta.api.IVESListAuthorizations
        - txp.bta.api.IVESViewAuthorization
        - txp.bta.api.IVESAuthorizeDocument
        - txp.bta.api.listBankAccounts
        - txp.bta.api.addBankAccount
        - txp.bta.api.removeBankAccount

      