openapi: 3.0.0
info:
  title: IRS Domain Data - Taxpayer Notice
  description: >-
    Service for IRS EDP Business Taxpayer Notice REST APIs
    Record notices sent to taxpayers after Designated Officer registration to enable verification from the address on record.
  version: '1.06.04'
servers:
  - url: /bus-acct-svcs-notice/api/v1/
paths:
  /taxpayer-notice-data:
    post:
      summary: Adds a new Taxpayer Notice
      description: >-
        Add a new Taxpayer Notice record
      operationId: addTaxpayerNotice
      parameters:
        - $ref: '#/components/parameters/enterpriseBusCorrelationId'
        - $ref: '#/components/parameters/apiCaller'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTaxpayerNotice'
            examples:
              taxpayerNoticeExample:
                $ref: '#/components/examples/RequestTaxpayerNoticeExample'
        required: true
      responses:
        '201':
          description: The notice was added successfully to the Taxpayer record.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseTaxpayerNotice'
              examples:
                taxpayerNoticeExample:
                  $ref: '#/components/examples/ResponseTaxpayerNoticeExample'
        '400':
          $ref: '#/components/responses/BadRequest'
        '412':
          $ref: '#/components/responses/PreconditionFailed'
      tags:
        - taxpayer
    put:
      summary: Update notice records
      description: >-
        Updates notice records associated with the taxpayer
      operationId: updateTaxpayerNotice
      parameters:
        - $ref: '#/components/parameters/enterpriseBusCorrelationId'
        - $ref: '#/components/parameters/apiCaller'
      requestBody:
        description: Update a Taxpayer notice
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTaxpayerNoticeList'
        required: true
      responses:
        '200':
          description: The notice was updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseTaxpayerNoticeList'
              examples:
                taxpayerNoticeExample:
                  $ref: '#/components/examples/ResponseTaxpayerNoticeExample'
        '400':
          $ref: '#/components/responses/BadRequest'
        '412':
          $ref: '#/components/responses/PreconditionFailed'
      tags:
        - taxpayer
    get:
      summary: Retrieve multiple records by status
      description: >-
        Retrieve multiple records by status
      operationId: getTaxpayerNotice
      parameters:
        - $ref: '#/components/parameters/enterpriseBusCorrelationId'
        - $ref: '#/components/parameters/apiCaller'
        - $ref: '#/components/parameters/noticeStatus'
        - $ref: '#/components/parameters/noticeType'
        - $ref: '#/components/parameters/fromNoticeDate'
        - $ref: '#/components/parameters/toNoticeDate'
      responses:
        '200':
          description: List of notices for ein/ssn
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseTaxpayerNoticeList'
              examples:
                taxpayerNoticeExample:
                  $ref: '#/components/examples/ResponseTaxpayerNoticeExample'
        '204':
          description: No records found
        '400':
          $ref: '#/components/responses/BadRequest'
        '412':
          $ref: '#/components/responses/PreconditionFailed'
      tags:
        - taxpayer
  /taxpayer-notice-data/version:
    get:
      summary: Returns a version number for the API
      description: Returns a version number of the API and the database
      operationId: TaxpayerVersion
      parameters:
        - $ref: '#/components/parameters/enterpriseBusCorrelationId'
        - $ref: '#/components/parameters/apiCaller'
      responses:
        '200':
          description: Here is the version information for this API
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/apiVersion'
      tags:
        - taxpayer
components:
  schemas:
    enterpriseBusCorrelationId:
      type: string
      pattern: >-
        [0-9a-zA-Z]{8}-[0-9a-zA-Z]{4}-[0-9a-zA-Z]{4}-[0-9a-zA-Z]{4}-[0-9a-zA-Z]{12}:[a-zA-Z0]{0,5}:[a-zA-Z0-9.*:]{0,19}:(T|B|O)
      example: 550e8400-e29b-41d4-a716-446655440000:AMS00:System1:T
    apiVersion:
      type: object
      properties:
        buildVersion:
          type: string
          example: v1.04.01
        debugLevel:
          type: integer
        environment:
          type: string
          enum:
            - Development
            - Test
            - Pre-Production
            - Production
        controller:
          type: string
          example: TaxpayerNotice
        buildDateTime:
          type: string
          format: date-time
          example: '2024-07-19T18:13:18Z'
        specificationVersion:
          type: string
          example: v1.04
        entityCount:
          type: integer
          example: 152726
        requestHost:
          type: string
          example: irs-edp-dev-api.a.cc.irs.gov
        requestUri:
          type: string
          example: /api/v1/tax-payer/version
        httpVerb:
          type: string
          example: GET
        serviceStart:
          type: string
          format: date-time
          example: '2024-07-19T18:39:18Z'
        serviceEnd:
          type: string
          format: date-time
          example: '2024-07-19T18:39:31Z'
        serviceElapsedTimeSec:
          type: number
          example: 1.49
    TIN:
      type: integer
      description: Taxpayer Identification Number
    TINType:
      type: string
      enum:
        - 'EIN'
        - 'SSN'
        - 'ITIN'
        - 'ATIN'
    NoticeStatus:
      type: string
      description: >-
        Status of the Notice
        Values: New, Sent to NOTCON
        Initializes to: 'New'
      enum:
        - New
        - Sent to NOTCON
    NoticeType:
      type: string
      description: Type of notice to be sent
      enum:
        - 'New Designated Officer'
    NoticeJSON:
      type: object
      description: JSON object containing the Notice data for the given notice type
    TaxpayerNoticeProperties:
      type: object
      description: The Taxpayer notice provided and returned by the service
      required:
        - guid
        - tin
        - tinType
        - status
        - noticeType
        - noticeJson
        - noticeTimestamp
      properties:
        guid:
          $ref: '#/components/schemas/GUID'
        tin:
          $ref: '#/components/schemas/TIN'
        tinType:
          $ref: '#/components/schemas/TINType'
        requesterTIN:
          $ref: '#/components/schemas/TIN'
        status:
          $ref: '#/components/schemas/NoticeStatus'
        noticeType:
          $ref: '#/components/schemas/NoticeType'
        noticeJson:
          $ref: '#/components/schemas/NoticeJSON'
        noticeTimestamp:
          type: string
          format: date-time
    NewTaxpayerNotice:
      allOf:
        - { $ref: '#/components/schemas/TaxpayerNoticeProperties' }
        - type: object
          required:
            - tin
            - tinType
            - status
            - noticeType
            - noticeJson
            - noticeTimestamp
    UpdateTaxpayerNotice:
      allOf:
        - { $ref: '#/components/schemas/TaxpayerNoticeProperties' }
        - type: object
          required:
            - guid
            - tin
            - tinType
            - status
            - noticeType
            - noticeJson
            - noticeTimestamp
    ResponseTaxpayerNotice:
      allOf:
        - { $ref: '#/components/schemas/TaxpayerNoticeProperties' }
        - type: object
          required:
            - guid
            - tin
            - tinType
            - requesterTIN
            - status
            - noticeType
            - noticeJson
            - noticeTimestamp
    UpdateTaxpayerNoticeList:
      type: array
      items:
        $ref: '#/components/schemas/UpdateTaxpayerNotice'
    ResponseTaxpayerNoticeList:
      type: array
      items:
        $ref: '#/components/schemas/ResponseTaxpayerNotice'
    GUID:
      type: string
      format: uuid
      description: 'The GUID of the object'
  examples:
    RequestTaxpayerNoticeExample:
      value:
        tin: '958473621'
        tinType: EIN
        requesterTIN: '135782468'
        status: New
        noticeType: 'New Designated Officer'
        noticeJSON: {}
        noticeTimestamp: '2024-07-19T18:39:18Z'
    ResponseTaxpayerNoticeExample:
      value:
        guid: '3fa85f64-5717-4562-b3fc-2c963f66afa6'
        tin: '958473621'
        tinType: EIN
        requesterTIN: null
        status: New
        noticeType: 'New Designated Officer'
        noticeJSON: {}
        noticeTimestamp: '2024-07-19T18:39:18Z'
  parameters:
    enterpriseBusCorrelationId:
      name: enterpriseBusCorrelationId
      description: Enterprise Business Correlation ID
      in: header
      required: false
      schema:
        $ref: '#/components/schemas/enterpriseBusCorrelationId'
    apiCaller:
      name: callingApplication
      description: >-
        the application that originally calls the API in a consistent, agreed
        upon naming convention
      in: header
      required: false
      schema:
        type: string
      example: Business-Online-Account
    noticeStatus:
      in: header
      description: >-
        The status of notice which was sent
      name: noticeStatus
      required: true
      schema:
        $ref: '#/components/schemas/NoticeStatus'
    noticeType:
      in: header
      description: >-
        The type of notice to be sent
      name: noticeType
      required: false
      schema:
        $ref: '#/components/schemas/NoticeType'
    fromNoticeDate:
      name: fromNoticeDate
      description: the starting posted date in the range of notices requested
      in: header
      required: false
      schema:
        type: string
        format: date
    toNoticeDate:
      name: toNoticeDate
      in: header
      description: the ending posted date in the range of noticed requested
      required: false
      schema:
        type: string
        format: date
  responses:
    BadRequest:
      description: This request was not formed correctly.
    PreconditionFailed:
      description: One of the required parameters is not correct.
    GeneralError:
      description: An error occurred
    VolumeExceeds:
      description: >-
        String.format("Too many records returned (%d) for the ein, max size:
        %d", recordsdatasetSize, API_MAX_DATASET_RETURN_LIMIT)
  headers:
    X-RateLimit-Limit:
      description: Request limit per hour
      schema:
        type: integer
      example: 100
    X-RateLimit-Remaining:
      description: Remaining requests for the hour
      schema:
        type: integer
      example: 94
  links: {}
  callbacks: {}
