openapi: 3.0.1
info:
  title: Transcripts
  description: 'This API provides operations supporting both the listing and retrieving of transcripts for a taxpayer, whether business, individual, or joint filers.'
  contact:
    name: IRS e-Services
    email: eservices.help@irs.gov
  version: '1'
servers:
- url: TBD
paths:
  '/transcript':
    get:
      tags:
        - List available transcripts
      summary: 'Search all available supported transcripts for a given TIN and TinType'
      description: 'Operation which will list all available supported transcripts/years for a given TIN and TIN type etc etc more defined later'
      parameters:
        - name: X-Tin
          in: header
          required: true
          schema:
            type: string
            pattern: '^\d{9}$'
        - name: X-Tin-Type
          in: header
          required: true
          schema:
            type: string
            enum:
              - SSN
              - EIN
        - name: year
          in: query
          description: Query parameter that allows the consumer to filter the transcripts list by year
          schema:
            type: string
            pattern: '^\d{4}$' 
        - name: transcriptType
          in: query
          description: Query parameter that allows the consumer to filter the transcripts list by type
          schema:
            $ref: '#/components/schemas/TranscriptType'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TranscriptsList'
        '204':
          description: No transcripts found for given TIN and TinType
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '405':
          description: Method Not Allowed
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '406':
          description: Not Acceptable
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '503':
          description: Service Unavailable 
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
  '/transcript/{type}/{taxperiod}/{mft}':
    get:
      tags:
        - Retrieve a transcript
      summary: 'Retrieve a transcript for the given TIN, tax year, transcript type, and MFT.'
      description: 'etc etc'
      parameters:
        - name: taxperiod
          in: path
          description: 'The requested tax period'
          required: true
          schema:
            type: string
            format: 'yyyyMM'
            pattern: '^\d{6}$'
        - name: type
          in: path
          description: 'The requested return type'
          required: true
          schema:
            $ref: '#/components/schemas/TranscriptType'
        - name: mft
          in: path
          description: 'The requested mft'
          required: true
          schema:
            $ref: '#/components/schemas/MFT'
        - name: X-Tin
          in: header
          required: true
          schema:
            type: string
            pattern: '^\d{9}$'
        - name: X-Tin-Type
          in: header
          required: true
          schema:
            type: string
            enum:
              - SSN
              - EIN
      responses:
        '200':
          description: The request completed successfully
          content:
            application/pdf: {}
            text/html: {}
            text/plain: {}
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '405':
          description: Method Not Allowed
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '406':
          description: Not Acceptable
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '503':
          description: Service Unavailable 
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'

components:
  schemas:
    ApiError:
      type: object
      properties:
        errorCode:
          type: string
        description:
          type: string
    ApiErrorResponse:
      type: object
      properties:
        status:
          type: integer
          format: int32
        message:
          type: string
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ApiError'
        timestamp:
          type: string
          format: date-time
    TranscriptsList:
      type: array
      items:
        $ref: '#/components/schemas/TranscriptSummary'
    TranscriptType:
      type: string
      enum:
        - 'return'
        - 'account'
        - 'recordOfAccount'
        - 'wageAndIncome'
    TranscriptSummary:
      type: object
      properties:
        transcriptType:
          $ref: '#/components/schemas/TranscriptType'
        taxPeriod:
          type: string
          format: 'yyyyMM'
        mft:
          $ref: '#/components/schemas/MFT'
        taxForm:
            $ref: '#/components/schemas/TaxForm'          
        _links:
          type: array
          items:
            $ref: '#/components/schemas/Link'
    MFT:
      type: string
      enum:       
        - "00"
        - "01"
        - "02"
        - "03"
        - "05"
        - "06"
        - "07"
        - "08"
        - "09"
        - "10"
        - "11"
        - "12"
        - "13"
        - "14"
        - "15"
        - "16"
        - "17"
        - "1A"
        - "21"
        - "25"
        - "26"
        - "27"
        - "28"
        - "29"
        - "30"
        - "31"
        - "32"
        - "33"
        - "34"
        - "36"
        - "37"
        - "42"
        - "43"
        - "44"
        - "46"
        - "50"
        - "52"
        - "55"
        - "60"
        - "63"
        - "64"
        - "65"
        - "66"
        - "67"
        - "71"
        - "72"
        - "73"
        - "74"
        - "75"
        - "77"
        - "78"
        - "79"
        - "80"
        - "81"
        - "82"
        - "83"
        - "84"
        - "85"
        - "86"
        - "90"
        - "91"
        - "92"
        - "93"
        - "94"
        - "95"
        - "96"
        - "97"
        - "98"   
    TaxForm:
      type: string
      enum:
        - "1040_SERIES"
        - "1041A"
        - "1041_SERIES"
        - "1042"
        - "1042-S"
        - "1065_SERIES"
        - "1066"
        - "1097-BTC"
        - "1098"
        - "1098-C"
        - "1098-E"
        - "1098-F"
        - "1098-Q"
        - "1098-T"
        - "1099-A"
        - "1099-B"
        - "1099-C"
        - "1099-CAP"
        - "1099-DIV"
        - "1099-G"
        - "1099-H"
        - "1099-INT"
        - "1099-K"
        - "1099-LS"
        - "1099-LTC"
        - "1099-MISC"
        - "1099-NEC"
        - "1099-OID"
        - "1099-PATR"
        - "1099-Q"
        - "1099-QA"
        - "1099-R"
        - "1099-S"
        - "1099-SA"
        - "1099-SB"
        - "1120_SERIES"
        - "11C"
        - "2290"
        - "3520A"
        - "3921"
        - "3922"
        - "4720"
        - "5227"
        - "5329"
        - "5498"
        - "5498-ESA"
        - "5498-SA"
        - "706"
        - "706GS(T)"
        - "706NA"
        - "720"
        - "730"
        - "8288"
        - "8752"
        - "8804"
        - "8805"
        - "940_SERIES"
        - "941"
        - "943"
        - "944"
        - "945"
        - "990"
        - "990C"
        - "990EZ"
        - "990PF"
        - "990T"
        - "ALL_FORMS"
        - "CIVIL_PENALTY"
        - "CT-1"
        - "K-1_1041"
        - "K-1_1065"
        - "K-1_1120S"
        - "SSA-1099"
        - "W-2"
        - "W-2G"
        - "W-4"              
    Link:
      type: object
      properties:
        href:
          type: string
        hreflang:
          type: string
        title:
          type: string
        type:
          type: string
        deprecation:
          type: string
        profile:
          type: string
        name:
          type: string
        templated:
          type: boolean
