/*
 * Name: ELRR
 * Date: 2021.08.06
 */

-- Navigate to elrr area
SET search_path = elrr;

-- Drop elrr tables
Drop table IF EXISTS ROLERELATIONS;
DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS ORGANIZATION;
DROP TABLE IF EXISTS LEARNERPROFILE;
DROP TABLE IF EXISTS CONTACTINFORMATION;
DROP TABLE IF EXISTS PERSON;
DROP TABLE IF EXISTS EMPLOYMENT;  
DROP TABLE IF EXISTS ELRRAUDITLOG; 
DROP TABLE IF EXISTS COURSE; 
DROP TABLE IF EXISTS COMPETENCY;
DROP TABLE IF EXISTS CONFIGURATION;
 