import com.deloitte.elrr.entity.Email;
import com.deloitte.elrr.entity.Identity;
import com.deloitte.elrr.entity.Credential;
import com.deloitte.elrr.entity.PersonalCredential;
import com.deloitte.elrr.entity.Person;
import com.deloitte.elrr.entity.types.LearningStatus;

import com.deloitte.elrr.elrraggregator.exception.ActivityNotFoundException;
import com.deloitte.elrr.elrraggregator.exception.PersonNotFoundException;
import com.deloitte.elrr.elrraggregator.exception.AggregatorException;

import java.lang.Exception

import java.util.Set;
import java.util.List;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Iterator;

import com.yetanalytics.xapi.model.AbstractActor;
import com.yetanalytics.xapi.model.AbstractObject;
import com.yetanalytics.xapi.model.Account;
import com.yetanalytics.xapi.model.Activity;
import com.yetanalytics.xapi.model.ActivityDefinition;
import com.yetanalytics.xapi.model.LangMap;
import com.yetanalytics.xapi.model.ObjectType;
import com.yetanalytics.xapi.model.Statement;
import com.yetanalytics.xapi.model.Verb;
import com.yetanalytics.xapi.model.Score;

global com.deloitte.elrr.jpa.svc.CredentialSvc credentialService;
global com.deloitte.elrr.jpa.svc.PersonalCredentialSvc personalCredentialService;

global com.deloitte.elrr.entity.Person person;
global com.yetanalytics.xapi.model.Statement statement;

global String verbId;
global String objType;
 
dialect "java"

rule "Process_Credential"
salience 90
   when
        Statement(verbId == "http://adlnet.gov/expapi/verbs/achieved")
        Statement(objType == "https://w3id.org/xapi/tla/activity-types/credential")
 
   then
        System.out.println("\n ==========Process Credential=============");
        System.out.println("rule triggered: " + drools.getRule().getName() + "\n");
        
        try {
        
            PersonalCredential personalCredential = null;
        
            ArrayList<String> languageCodes = new ArrayList<String>();
            languageCodes.add("en-us");
            languageCodes.add("en");
          
            // Process credential
            System.out.println("Process credential.");
    
            // Get activity
            Activity activity = (Activity) statement.getObject();
    
            System.out.println("Person " + person.getName() + " exists.");
    
            // Activity Definition
            ActivityDefinition activityDefenition = activity.getDefinition();
    
            String activityName = "";
            String activityDescription = "";
            String nameLangCode = null;
            String descLangCode = null;
            
            LangMap nameLangMap = null;
    
            try {
              nameLangMap = activityDefenition.getName();
            } catch (ClassCastException | NullPointerException e) {
              System.out.println(e.getMessage());
              e.printStackTrace();
              throw new AggregatorException("Error processing competency - " + e.getMessage());
            }
    
            // If Activity name
            if (nameLangMap != null) {
            
              Set<String> nameLangCodes = nameLangMap.getLanguageCodes();
    
              // Get namLangCode
              Iterator<String> nameLangCodesIterator = nameLangCodes.iterator();
    
              while (nameLangCodesIterator.hasNext()) {
              
                String code = nameLangCodesIterator.next();
                
                if (languageCodes.contains(code)) {
                    nameLangCode = code;
                    break;
                }
                
              }
    
              if (nameLangCode == null || nameLangCode.length() == 0) {
              
                // Check for en-us then en
                if (nameLangCodes.contains("en-us")) {
                
                  nameLangCode = "en-us";
    
                } else if (nameLangCodes.contains("en")) {
                
                  nameLangCode = "en";
    
                } else {
                  String firstElement =
                  nameLangCodes.stream().findFirst().orElse(null);
                  nameLangCode = firstElement;
                }
    
              } // if (nameLangCode == null || nameLangCode.length() == 0) {
    
              activityName = activityDefenition.getName().get(nameLangCode);
    
            } else {
              activityName = "";
            } // if (nameLangMap != null) {
            
            LangMap descLangMap = null;
    
            try {
              descLangMap = activity.getDefinition().getDescription();
            } catch (ClassCastException | NullPointerException e) {
              System.out.println(e.getMessage());
              e.printStackTrace();
              throw new AggregatorException("Error processing competency - " + e.getMessage());
            }
    
            // If Activity description
            if (descLangMap != null) {
            
              Set<String> descLangCodes = descLangMap.getLanguageCodes();
    
              // Get descLangCode
              Iterator<String> descLangCodesIterator = descLangCodes.iterator();
    
              while (descLangCodesIterator.hasNext()) {
              
                String code = descLangCodesIterator.next();
                
                if (languageCodes.contains(code)) {
                    descLangCode = code;
                    break;
                }
                
              }
    
              if (descLangCode == null || descLangCode.length() == 0) {
              
                // Check for en-us then en
                if (descLangCodes.contains("en-us")) {
                
                  descLangCode = "en-us";
    
                } else if (descLangCodes.contains("en")) {
                
                  descLangCode = "en";
    
                } else {
                  String firstElement =
                  descLangCodes.stream().findFirst().orElse(null);
                  descLangCode = firstElement;
                }
    
              } // if (descLangCode == null || descLangCode.length() == 0) {
    
              activityDescription = activityDefenition.getDescription().get(nameLangCode);
    
            } else {
              activityDescription = "";
            } // if (descLangMap != null) {
 
            // Get credential
            Credential credential = credentialService.findByIdentifier(activity.getId());

            // If credential exists exist
            if (credential != null) {
                System.out.println("Credential " + activity.getId() + " exists.");
            
                credential.setFrameworkTitle(activityName);
                credential.setFrameworkDescription(activityDescription);
                credentialService.update(credential);
                System.out.println("Credential " + activity.getId() + " updated.");
          
            // If credential doesn't exist
            } else if (credential == null) {
                System.out.println("Creating new credential.");
 
                credential = new Credential();
                credential.setIdentifier(activity.getId());
                credential.setFrameworkTitle(activityName);
                credential.setFrameworkDescription(activityDescription);
                credentialService.save(credential);
                System.out.println("Credential " + activity.getId() + " created.");
    
          } // if (credential == null) {
    
          // If Credential already exists
          if (credential != null) {
          
            // Get PersonalCredential
            personalCredential =
                personalCredentialService.findByPersonIdAndCredentialId(person.getId(), credential.getId());
   
            // If PersonalCredential doesn't exist
            if (personalCredential == null) {
            
              System.out.println("Creating new personal credential.");
              
              personalCredential = new PersonalCredential();
              personalCredential.setPerson(person);
              personalCredential.setCredential(credential);
              personalCredential.setHasRecord(true);
              personalCredentialService.save(personalCredential);
    
              System.out.println("Personal Credential for " + person.getName() + " - "
                  + credential.getFrameworkTitle() + " created.");
    
            }
    
          } // if (credential != null) {
        
        } catch (Exception e) {
          System.out.println("Exception while firing processStatement rule.");
          e.printStackTrace();
          throw new AggregatorException("while firing processStatement rule - " + e.getMessage());
        }

  end