name: Deploy to AWS
on:
 push:
   branches:
     - main
jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout Code
       uses: actions/checkout@v2
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v2
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1
     - name: Deploy Application
       run: |
         aws s3 cp ./build s3://your-s3-bucket-name --recursive
         aws deploy create-deployment \
           --application-name YourAppName \
           --deployment-group-name YourDeploymentGroup \
           --s3-location bucket=your-s3-bucket-name,key=build.zip,bundleType=zip